GRANT USAGE ON SCHEMA spat TO mapaosc;
GRANT USAGE ON SCHEMA olap TO mapaosc;
GRANT USAGE ON SCHEMA data TO mapaosc;
GRANT USAGE ON SCHEMA portal TO mapaosc;
GRANT USAGE ON SCHEMA syst TO mapaosc;
GRANT SELECT ON ALL TABLES IN SCHEMA spat TO mapaosc;
GRANT SELECT ON ALL TABLES IN SCHEMA olap TO mapaosc;
GRANT SELECT ON ALL TABLES IN SCHEMA data TO mapaosc;
GRANT SELECT ON ALL TABLES IN SCHEMA portal TO mapaosc;
GRANT INSERT ON ALL TABLES IN SCHEMA portal TO mapaosc;
GRANT UPDATE ON ALL TABLES IN SCHEMA portal TO mapaosc;
GRANT USAGE ON SEQUENCE portal.tb_usuario_tusu_sq_usuario_seq TO mapaosc;
GRANT SELECT ON ALL TABLES IN SCHEMA syst TO mapaosc;

